### ISSUE TITLE
Error "Invalid parameter = prod" 

### ISSUE THREAD

**Issue by anilshivaraj** [trailheadapps/ebikes-manufacturing#142]
### Summary

I am getting the error "Invalid parameter = prod error," when running the node server on a windows machine

### Steps To Reproduce

Followed the steps exactly mentioned

- Create a .env file at the root of the ebikes-manufacturing project
- Updated the property values by referring to the [configuration reference](https://github.com/trailheadapps/ebikes-manufacturing#configuration-reference) section
- Install the project with npm install
- Run the project with npm start

### Current Behavior

![image](https://github.com/trailheadapps/ebikes-manufacturing/assets/5904682/1f869815-af0a-491b-9474-6b2c52640a14)

### Relevant Log Output

```shell
PS C:\Users\anils1\Documents\code\ebikes-manufacturing> npm start

> lwc-oss-manufacturing@1.0.0 start  
> MODE=prod node src/server/server.js

Invalid parameter - =prod
PS C:\Users\anils1\Documents\code\ebikes-manufacturing>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pozil** [comment]
@anilshivaraj sorry about this. It was another problem with Windows but I fixed it. Can you get the latest version and reinstall. The build should now support all OSes.
